### ISSUE TITLE
Species Portfolio task list

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/PortfolioKiri#9]
- [x] Build loop to build portfolio by BGC by Site Series from submitted data points
- [x] Output portfolio by BGC for all site series in a grid layout.
- [x] Calculate the ratio of species at a set % productivity level (90%) to start will.
- [x] Output species ratio in formatted table by BGC x Site Series
- [x] Make CCISS a function so that this code can be called from the portfolio for selected set of points and returns the predicted species data
- [x] Add map showing submitted points to start of script

**Comment by kdaust** [comment]
I think the max sharpe ratio is a better way to select a point on the frontier, but we can also add option to do it by specified return
